### ISSUE TITLE
Elm / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#41]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/elm/blob/master/README.md). (Look for "Elm icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/elm/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by JoelQ** [comment]
### Official Logo
The official logo is the **Tangram**. It is mostly commonly seen in it's multi-colored version (as seen in the favicon on http://elm-lang.org ) although it is also used in a monochromatic form (as seen in the header on http:// elm-lang.org )

Monochrome:
![](http://elm-lang.org/assets/logo.svg)

Color:
![](http://package.elm-lang.org/assets/elm_logo.svg)

### Unofficial Logo

The community commonly remixes the Tangram logo in various forms to create custom logos for elm-lang projects, events, or even just for fun.

For example:

http://elm-community.org/
![](http://elm-community.org/assets/tangram-runner.png)

http://www.elmweekly.nl/
![](https://uploads.goodbits.io/uploads/landing_site/logo/6399/e47af011-7a52-4066-98cf-8b3e044ab33e.png)

https://elmeurope.org/
![](https://elmeurope.org/events/87/logo.png)

There's even a library for drawing the official logo and variations programatically https://github.com/ElmLive/tangram-logo

### Link to Logo

* [Monochrome Logo SVG](https://github.com/elm-lang/elm-lang.org/blob/master/assets/logo.svg)
* [Color Logo SVG](https://github.com/elm-lang/package.elm-lang.org/blob/master/assets/elm_logo.svg)
* [Color Logo PNG](https://github.com/elm-lang/package.elm-lang.org/blob/master/assets/logo.png)

### License, Usage Rights

Both the monochromatic logo (in SVG form) and colored logo (in .ico form) are on the GitHub repo for the elm-lang.org website https://github.com/elm-lang/elm-lang.org. The colored logo also shows up in colored in both SVG and PNG forms in the repo for the package website https://github.com/elm-lang/package.elm-lang.org 

Both repos are distributed under the **BSD 3-Clause** license. Not sure how this affects the usage rights of the images?

Wikipedia thinks the logo **does not meets the requirements for copyright** because it is simply geometric shapes: https://commons.wikimedia.org/wiki/File:Elm_logo.svg

**Comment by iHiD** [comment]
Ha. This is excellent. Thank you so much for all the detail.
