### ISSUE TITLE
Perl 5 / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#64]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/perl5/blob/master/README.md). (Look for "Perl 5 icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/perl5/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by cowens** [comment]
### Official Logo

The Perl Foundation's official logo is an [Onion](http://www.perlfoundation.org/perl_trademark).

### Unofficial Logo

Due to the cover of O'Reilly's Programming Perl, a [Camel](http://archive.oreilly.com/pub/a/oreilly/perl/usage/) is often associated with Perl 5. 

Perl 5 also has an unofficial logo of a [raptor](https://github.com/kraih/perl-raptor) due to keynote speech given by [MST](http://shadow.cat/blog/matt-s-trout/).

### Link to Logo

#### Onion

http://www.perlfoundation.org/attachment/perl_trademark/powered_by_perl-300px.png

#### Camel

http://archive.oreilly.com/images/perl/camel.gif

#### Raptor

https://raw.githubusercontent.com/kraih/perl-raptor/master/raptor.svg

### License, Usage Rights

#### Onion

Owned by the Perl Foundation, see http://www.perlfoundation.org/perl_trademark for usage information.

#### Camel

Owned by O'Reilly, see http://archive.oreilly.com/pub/a/oreilly/perl/usage/ for usage information.

#### Raptor

CC-SA License, see https://github.com/kraih/perl-raptor/blob/master/README.md and http://creativecommons.org/licenses/by-sa/4.0

**Comment by iHiD** [comment]
Very informative. Thank you so much.
